### ISSUE TITLE
Re-add template-specific configs

### ISSUE THREAD

**Issue by sbonami** [RootsRated/stevenson#6]
We had really cool logic for configuring templates individually. Should definitely add this back in:

https://github.com/RootsRated/stevenson/commit/7939aa3f225711d2742a444883786e8229f74145
https://github.com/RootsRated/stevenson/commit/3b3f4e411541a10c4b4a9c52035a2c9ec59616d6

**Comment by wleklinski** [comment]
Should we add this really cool logic back in? 🥇

**Comment by sbonami** [comment]
Huh?
